name = "test-borrower-api"
main = "src/index.js"
node_compat = true
compatibility_date = "2022-08-17"

kv_namespaces = [
    { binding = "PROFILES", id = "59fbb914d6204889a94aee08e89e5c21", preview_id = "fc688276b1da4e98a35e13aa83b825e3"}
]

[vars]
ORIGIN = "*"
RPC_URL = "https://matic-mumbai.chainstacklabs.com"
CORE_ACCESS_CONTROL="0x81b8107153F5d53b8aAA0b9b6A3391DFAAf43C84"

[env.staging]
name = "test-borrower-api"
kv_namespaces = [
    { binding = "PROFILES", id = "59fbb914d6204889a94aee08e89e5c21", preview_id = "fc688276b1da4e98a35e13aa83b825e3"}
]
[env.staging.vars]
ORIGIN = "https://saplingteam.github.io"
RPC_URL = "https://matic-mumbai.chainstacklabs.com"
CORE_ACCESS_CONTROL="0x81b8107153F5d53b8aAA0b9b6A3391DFAAf43C84"

[env.production]
name = "borrower-api"
kv_namespaces = [
    { binding = "PROFILES", id = "c75217d882224e5f86762140bf08a19f"}
]
[env.production.vars]
ORIGIN = "https://app.sapling.finance"
RPC_URL = "https://polygon-rpc.com/"
CORE_ACCESS_CONTROL=""

